#!/usr/bin/env python3
"""
Sync the "数据源抓取与有效性（过去24小时）" section in a digest report
from a candidate JSON file generated by collect_news.py.
"""

from __future__ import annotations

import argparse
import json
import re
import urllib.parse
from pathlib import Path
from typing import Any


SECTION_TITLE = "## 数据源抓取与有效性（过去24小时）"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Update source-health section in markdown digest from candidate JSON."
    )
    parser.add_argument("--report", required=True, help="Path to markdown digest report")
    parser.add_argument(
        "--candidate-json",
        default="",
        help="Optional explicit candidate JSON path. If omitted, use latest in --inbox-dir.",
    )
    parser.add_argument(
        "--inbox-dir",
        default="./data/inbox",
        help="Directory containing news_candidates_*.json files",
    )
    return parser.parse_args()


def latest_candidate_file(inbox_dir: str) -> Path:
    root = Path(inbox_dir)
    files = sorted(root.glob("news_candidates_*.json"))
    if not files:
        raise FileNotFoundError(f"No candidate files found under: {root}")
    return files[-1]


def load_candidate(path: Path) -> dict[str, Any]:
    if not path.exists():
        raise FileNotFoundError(f"Candidate JSON not found: {path}")
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError("Candidate JSON root must be an object")
    if not isinstance(data.get("fetch_report"), list):
        raise ValueError("Candidate JSON missing fetch_report list")
    return data


def url_host(url: str) -> str:
    if not url:
        return ""
    try:
        return urllib.parse.urlsplit(url).netloc
    except Exception:
        return ""


def trim_error(text: str, limit: int = 240) -> str:
    value = (text or "").strip().replace("\n", " ")
    return value if len(value) <= limit else value[:limit] + "..."


def build_section(candidate_path: Path, payload: dict[str, Any]) -> str:
    stats = payload.get("stats", {}) if isinstance(payload.get("stats"), dict) else {}
    fetch_report = payload.get("fetch_report", [])
    ok_rows = [row for row in fetch_report if isinstance(row, dict) and row.get("status") == "ok"]
    err_rows = [row for row in fetch_report if isinstance(row, dict) and row.get("status") != "ok"]

    lines: list[str] = []
    lines.append(SECTION_TITLE)
    lines.append(
        f"- 数据窗口: {payload.get('window_start', '')} -> {payload.get('window_end', '')}"
    )
    lines.append(f"- 候选总数（去重后）: {stats.get('total_after_dedup', 0)}")
    lines.append(f"- 候选文件: {candidate_path.name}")
    lines.append("### 成功抓取（本次进入候选池并参与筛选）")

    if ok_rows:
        for row in ok_rows:
            source = str(row.get("source", "Unknown")).strip() or "Unknown"
            host = url_host(str(row.get("url", "")).strip())
            host_info = f" ({host})" if host else ""
            fetched = row.get("fetched", 0)
            mode = str(row.get("mode", "")).strip()
            mode_info = f", mode={mode}" if mode else ""
            lines.append(f"- {source}{host_info} - status: ok, fetched: {fetched}{mode_info}")
    else:
        lines.append("- 无")

    lines.append("### 抓取失败或不可用（建议排查）")
    if err_rows:
        for row in err_rows:
            source = str(row.get("source", "Unknown")).strip() or "Unknown"
            host = url_host(str(row.get("url", "")).strip())
            host_info = f" ({host})" if host else ""
            err = trim_error(str(row.get("error", "unknown error")))
            lines.append(f"- {source}{host_info} - status: error, {err}")
    else:
        lines.append("- 无")

    return "\n".join(lines).rstrip() + "\n"


def section_end(text: str, start_index: int) -> int:
    next_header = re.search(r"^##\s+", text[start_index + 1 :], flags=re.MULTILINE)
    if not next_header:
        return len(text)
    return start_index + 1 + next_header.start()


def replace_or_insert_section(text: str, section_markdown: str) -> str:
    section_match = re.search(r"^##\s+数据源抓取与有效性（过去24小时）\s*$", text, flags=re.MULTILINE)
    body = text
    if section_match:
        start = section_match.start()
        end = section_end(text, start)
        body = (text[:start] + text[end:]).strip() + "\n"

    # Always append source-health section at the end to keep primary news sections first.
    return body.rstrip() + "\n\n" + section_markdown + "\n"


def main() -> int:
    args = parse_args()
    report_path = Path(args.report)
    if not report_path.exists():
        raise FileNotFoundError(f"Report file not found: {report_path}")

    candidate_path = (
        Path(args.candidate_json)
        if args.candidate_json.strip()
        else latest_candidate_file(args.inbox_dir)
    )
    payload = load_candidate(candidate_path)

    report_text = report_path.read_text(encoding="utf-8")
    new_section = build_section(candidate_path=candidate_path, payload=payload)
    updated = replace_or_insert_section(text=report_text, section_markdown=new_section)
    report_path.write_text(updated, encoding="utf-8")

    print(f"[OK] Source-health section synced from: {candidate_path}")
    print(f"[OK] Updated report: {report_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
